### PR TITLE
Website

### PR DESCRIPTION
**Pull request by Creatune**

### CODE REVIEW

**Comment by srevinsaju** [comment]
Is the work on the PR over?

**Comment by srevinsaju** [comment]
Oops, I closed it on mistake

**Comment by Creatune** [comment]
No
I have a few more commits

**Comment by srevinsaju** [comment]
Ok

**Comment by Creatune** [comment]
For now, this is what I have completed. In a later PR I will add functionality to the buttons.

**Comment by Creatune** [comment]
So this PR is done for now. You can merge it

**Comment by Creatune** [comment]
Screenshot from 2020-03-20 18-30-47

Here is the current webpage

**Pull request merged**
